### PR TITLE
Windows fixed with setup_env.bat

### PR DESCRIPTION
**Pull request by KingArrkinian**
The HAL Plugins are now found thanks to setup_env.bat.

The issue with the oversized numpy arrays still stands for 8 tests in pytests_core.

### CODE REVIEW

**Comment by KingArrkinian** [comment]
Small confirmation: having PR'd successfully once, I still cannot assign reviewers, labels, or milestones.
Github relies on the repository owner's CM.

**Comment by KingArrkinian** [comment]
Closing to test if this cancels the PR workflows.

**Comment by KingArrkinian** [comment]
Notes:
- The action on Windows will still fail from timeout due to the ongoing HAL_CREDENTIALS secret that will not work from a fork. This will be replaced by a stub requiring no secret, so it is left as is for now. It will however not be a problem for internal merges.
- The CI bot has been removed to let the official Github for Slack integration bot take over.
- Temporarily, and following best practices, the HAL_CREDENTIALS have been passed into its step's env. This best practice avoids tampering with the value through a script modification.

**Review by cbernard-psee — APPROVED** [review]
PR approved. Intermediate step so a new branch can be created under github_actions and worflow updated to fix Windows stage

**Pull request merged**
