### PR TITLE
[ISSUE-17] [DEV] Reduced allocted ringbuffer sizes in rawreader_pytest

### PR DESCRIPTION
**Pull request by nbourdis-psee**
Updated rawreader_pytest.py to fix the Windows stage of the Github Actions pipeline.

### CODE REVIEW

**Review by KingArrkinian — COMMENTED** [review]
The file has multiple 
    video = RawReader(filename, do_time_shifting=True)
    raw_evs = **video.load_n_events(1E8)**
Will that be a problem if we switch video size to 1e7?
https://github.com/prophesee-ai/openeb/blob/main/sdk/modules/core/python/tests/raw_reader_pytest.py

**Comment by nbourdis-psee** [comment]
Indeed, I had a closer look and I think this is fine. We'll see with the builds and I'll update if needed.

**Review by KingArrkinian — APPROVED** [review]

**Comment by KingArrkinian** [comment]
**All Build / Windows (pull_request) Successful in 12m
All Build / Windows (push) Successful in 11m**
https://nevergrind.com/blog/wp-content/uploads/2015/07/m-bison-yes.gif

**Comment by laurentbristiel** [comment]
Superseeded by https://github.com/prophesee-ai/openeb/pull/31 => closing

**Pull request closed without merging**
